--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Taylor-pm-pl/Bing-AI
build-by-default: true
branches:
- main
projects:
  Bing-AI:
    path: ""
    icon: icon.png
    includeDirs:
      vendor: vendor
...
